apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "simple", "namespace": "", "kind": "DeploymentConfig"}]'
      name: demo-web-pipeline
    spec:
      source:
        git:
          ref: master
          uri: https://github.com/jarekpc/demo-web.git
        type: Git
      strategy:
        type: JenkinsPipeline
        jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile
      triggers:
        - generic:
            secret: haslo
          type: Generic